include ../../Environment.mk
SOURCE=test
SUFFIX=.py
D_LINKS_PATH=/home/ben/.local/lib/python3.10/site-packages/numba/core/runtime/
D_LINKS=-lm -l_nrt_python.cpython-310-x86_64-linux-gnu
INCLUDE=-I$(TRACEATLAS_ROOT)include/Profile/Backend/Utilities/ -I../../TimingLib/
POLLY_SHOW=
include ../../BuildFlow.mk
