include ../../Environment.mk

SOURCE=backprop
ADDSOURCE=local_support.c ../common/support.c ../common/harness.c
INCLUDE=-I../common/
RARGS=input.input_data check.input_data
D_LINKS=-lm

include ../../BuildFlow.mk
