include ../../../Environment.mk

SOURCE=kmp
ADDSOURCE=local_support.c ../../common/support.c ../../common/harness.c
INCLUDE=-I../../common/
RARGS=input.input_data check.input_data

include ../../../BuildFlow.mk
