
GSL_ROOT=/mnt/heorot-10/bwilli46/dash-archives/debug/gsl/
SOURCE=heapsort

D_LINKS=-lm
INCLUDE=\
-I$(TRACEATLAS_ROOT)include/\
-I$(GSL_ROOT)include/
LIBRARIES=\
$(GSL_ROOT)lib/libgsl.a\

include ../../../BuildFlow.mk
