include ../../../Environment.mk

CFLAGS+=-std=c++17
SOURCE=fft
ADDSOURCE=fft.cpp
SUFFIX=.cpp

INCLUDE=-I../../../lib/Halide/include/

DEBUG=-g0
OPFLAG=-O3
AUTOSCHEDULE=0
HALIDE=1

include ../../../BuildFlow.mk
