include ../../../Environment.mk

KERN=bfs
ALG=queue

CFLAGS?=-O3 -Wall -Wno-unused-label
SOURCE=bfs
ADDSOURCE=local_support.c ../../common/support.c ../../common/harness.c
INCLUDE=-I../../common/
RARGS=input.input_data check.input_data

include ../../../BuildFlow.mk
