include ../../Environment.mk

SOURCE=HoughTransform
INPUT_IMAGE=../../Bilateral_Filter/Data/john.pnm
OUTPUT_IMAGE=../../Bilateral_Filter/Data/filtered_john.pnm
RARGS=$(INPUT_IMAGE) $(OUTPUT_IMAGE)

POLLY_SHOW=
include ../../BuildFlow.mk
